UPDATE TB_CAMPEONATO_PARAM SET DC_URL_FETCH_JOGOS = 'http://www.tabeladobrasileirao.net/2014/' WHERE ID_CAMPEONATO = 1;
UPDATE TB_CAMPEONATO_PARAM SET DC_URL_FETCH_JOGOS = 'http://www.tabeladobrasileirao.net/2015/' WHERE ID_CAMPEONATO = 2;
UPDATE TB_CAMPEONATO_PARAM SET DC_URL_FETCH_JOGOS = 'http://www.tabeladobrasileirao.net/2016/' WHERE ID_CAMPEONATO = 3;